databases:
  - name: telemedicine-db
    databaseName: telemedicine
    user: telemedicine_user

services:
  - type: web
    name: telemedicine-app
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python scripts/init_db.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: telemedicine-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    healthCheckPath: /